//
// This file was generated by ExtUtils::ParseXS (version 3.16) and 
// then manually edited to be visually cleaner.
//

#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

STATIC XSPROTO(the_desired_add_function) {
//  dVAR; 

    dXSARGS;

    if (items != 2) {
         croak_xs_usage(cv,  "a, b");
    }

	  double	returned_value;
	  dXSTARG;

//  ---------------------------
//  Pull arguments from stack:
	  double	a = (double) SvNV(ST(0));
	  double	b = (double) SvNV(ST(1));
//  ---------------------------


//  ---------------------------
//  THIS is the actual addition
    returned_value = a+b;
//  ---------------------------

	  XSprePUSH; 
    
    PUSHn((double) returned_value);

    XSRETURN(1);
}


XSPROTO(boot_theDesired) {
//  dVAR; 

    dXSARGS;

    PERL_UNUSED_VAR(cv);
    PERL_UNUSED_VAR(items);

    XS_APIVERSION_BOOTCHECK;

//  --------------------------------
//  Tell the environment what function (function pointer)
//  to call when XSLoaderTest::add is
//  requested;
    newXS("XSLoaderTest::add", the_desired_add_function, __FILE__);
//  --------------------------------

    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
      XSRETURN_YES;
}
