perl parseOSMFile.pl c:\temp\switzerland.osm.0
perl parseOSMFile.pl c:\temp\switzerland.osm.1
perl parseOSMFile.pl c:\temp\switzerland.osm.2
perl parseOSMFile.pl c:\temp\switzerland.osm.3
perl parseOSMFile.pl c:\temp\switzerland.osm.4
perl parseOSMFile.pl c:\temp\switzerland.osm.5
perl parseOSMFile.pl c:\temp\switzerland.osm.6
perl parseOSMFile.pl c:\temp\switzerland.osm.7
perl parseOSMFile.pl c:\temp\switzerland.osm.8
perl parseOSMFile.pl c:\temp\switzerland.osm.9
perl parseOSMFile.pl c:\temp\switzerland.osm.10
perl parseOSMFile.pl c:\temp\switzerland.osm.11
perl parseOSMFile.pl c:\temp\switzerland.osm.12
perl parseOSMFile.pl c:\temp\switzerland.osm.13
perl parseOSMFile.pl c:\temp\switzerland.osm.14
perl parseOSMFile.pl c:\temp\switzerland.osm.15
perl parseOSMFile.pl c:\temp\switzerland.osm.16
perl parseOSMFile.pl c:\temp\switzerland.osm.17
perl parseOSMFile.pl c:\temp\switzerland.osm.18
perl parseOSMFile.pl c:\temp\switzerland.osm.19
perl parseOSMFile.pl c:\temp\switzerland.osm.20
perl parseOSMFile.pl c:\temp\switzerland.osm.21
perl parseOSMFile.pl c:\temp\switzerland.osm.22
perl parseOSMFile.pl c:\temp\switzerland.osm.23
perl parseOSMFile.pl c:\temp\switzerland.osm.24
perl parseOSMFile.pl c:\temp\switzerland.osm.25
perl parseOSMFile.pl c:\temp\switzerland.osm.26
perl parseOSMFile.pl c:\temp\switzerland.osm.27
perl parseOSMFile.pl c:\temp\switzerland.osm.28
perl parseOSMFile.pl c:\temp\switzerland.osm.29
perl parseOSMFile.pl c:\temp\switzerland.osm.30
perl parseOSMFile.pl c:\temp\switzerland.osm.31
perl parseOSMFile.pl c:\temp\switzerland.osm.32
perl parseOSMFile.pl c:\temp\switzerland.osm.33
perl parseOSMFile.pl c:\temp\switzerland.osm.34
perl parseOSMFile.pl c:\temp\switzerland.osm.35
perl parseOSMFile.pl c:\temp\switzerland.osm.36
perl parseOSMFile.pl c:\temp\switzerland.osm.37
perl parseOSMFile.pl c:\temp\switzerland.osm.38
perl parseOSMFile.pl c:\temp\switzerland.osm.39
perl parseOSMFile.pl c:\temp\switzerland.osm.40
perl parseOSMFile.pl c:\temp\switzerland.osm.41
perl parseOSMFile.pl c:\temp\switzerland.osm.42
perl parseOSMFile.pl c:\temp\switzerland.osm.43
perl parseOSMFile.pl c:\temp\switzerland.osm.44
perl parseOSMFile.pl c:\temp\switzerland.osm.45
perl parseOSMFile.pl c:\temp\switzerland.osm.46
perl parseOSMFile.pl c:\temp\switzerland.osm.47
perl parseOSMFile.pl c:\temp\switzerland.osm.48
perl parseOSMFile.pl c:\temp\switzerland.osm.49
perl parseOSMFile.pl c:\temp\switzerland.osm.50
perl parseOSMFile.pl c:\temp\switzerland.osm.51
perl parseOSMFile.pl c:\temp\switzerland.osm.52
perl parseOSMFile.pl c:\temp\switzerland.osm.53
perl parseOSMFile.pl c:\temp\switzerland.osm.54
perl parseOSMFile.pl c:\temp\switzerland.osm.55
perl parseOSMFile.pl c:\temp\switzerland.osm.56
perl parseOSMFile.pl c:\temp\switzerland.osm.57
perl parseOSMFile.pl c:\temp\switzerland.osm.58
perl parseOSMFile.pl c:\temp\switzerland.osm.59
perl parseOSMFile.pl c:\temp\switzerland.osm.60
perl parseOSMFile.pl c:\temp\switzerland.osm.61
perl parseOSMFile.pl c:\temp\switzerland.osm.62
perl parseOSMFile.pl c:\temp\switzerland.osm.63
perl parseOSMFile.pl c:\temp\switzerland.osm.64
perl parseOSMFile.pl c:\temp\switzerland.osm.65
perl parseOSMFile.pl c:\temp\switzerland.osm.66
perl parseOSMFile.pl c:\temp\switzerland.osm.67
perl parseOSMFile.pl c:\temp\switzerland.osm.68
perl parseOSMFile.pl c:\temp\switzerland.osm.69
perl parseOSMFile.pl c:\temp\switzerland.osm.70
perl parseOSMFile.pl c:\temp\switzerland.osm.71
perl parseOSMFile.pl c:\temp\switzerland.osm.72
perl parseOSMFile.pl c:\temp\switzerland.osm.73
perl parseOSMFile.pl c:\temp\switzerland.osm.74
perl parseOSMFile.pl c:\temp\switzerland.osm.75
perl parseOSMFile.pl c:\temp\switzerland.osm.76
perl parseOSMFile.pl c:\temp\switzerland.osm.77
perl parseOSMFile.pl c:\temp\switzerland.osm.78
perl parseOSMFile.pl c:\temp\switzerland.osm.79
perl parseOSMFile.pl c:\temp\switzerland.osm.80
perl parseOSMFile.pl c:\temp\switzerland.osm.81
perl parseOSMFile.pl c:\temp\switzerland.osm.82
perl parseOSMFile.pl c:\temp\switzerland.osm.83
perl parseOSMFile.pl c:\temp\switzerland.osm.84
perl parseOSMFile.pl c:\temp\switzerland.osm.85
perl parseOSMFile.pl c:\temp\switzerland.osm.86
perl parseOSMFile.pl c:\temp\switzerland.osm.87
perl parseOSMFile.pl c:\temp\switzerland.osm.88
perl parseOSMFile.pl c:\temp\switzerland.osm.89
perl parseOSMFile.pl c:\temp\switzerland.osm.90
perl parseOSMFile.pl c:\temp\switzerland.osm.91
perl parseOSMFile.pl c:\temp\switzerland.osm.92
perl parseOSMFile.pl c:\temp\switzerland.osm.93
perl parseOSMFile.pl c:\temp\switzerland.osm.94
perl parseOSMFile.pl c:\temp\switzerland.osm.95
perl parseOSMFile.pl c:\temp\switzerland.osm.96
perl parseOSMFile.pl c:\temp\switzerland.osm.97
perl parseOSMFile.pl c:\temp\switzerland.osm.98
perl parseOSMFile.pl c:\temp\switzerland.osm.99
perl parseOSMFile.pl c:\temp\switzerland.osm.100


perl parseOSMFile.pl  c:\temp\switzerland.osm.101
perl parseOSMFile.pl  c:\temp\switzerland.osm.102
perl parseOSMFile.pl  c:\temp\switzerland.osm.103
perl parseOSMFile.pl  c:\temp\switzerland.osm.104
perl parseOSMFile.pl  c:\temp\switzerland.osm.105
perl parseOSMFile.pl  c:\temp\switzerland.osm.106
perl parseOSMFile.pl  c:\temp\switzerland.osm.107
perl parseOSMFile.pl  c:\temp\switzerland.osm.108
perl parseOSMFile.pl  c:\temp\switzerland.osm.109
perl parseOSMFile.pl  c:\temp\switzerland.osm.110
perl parseOSMFile.pl  c:\temp\switzerland.osm.111
perl parseOSMFile.pl  c:\temp\switzerland.osm.112
perl parseOSMFile.pl  c:\temp\switzerland.osm.113
perl parseOSMFile.pl  c:\temp\switzerland.osm.114
perl parseOSMFile.pl  c:\temp\switzerland.osm.115
perl parseOSMFile.pl  c:\temp\switzerland.osm.116
perl parseOSMFile.pl  c:\temp\switzerland.osm.117
perl parseOSMFile.pl  c:\temp\switzerland.osm.118
perl parseOSMFile.pl  c:\temp\switzerland.osm.119
perl parseOSMFile.pl  c:\temp\switzerland.osm.120
perl parseOSMFile.pl  c:\temp\switzerland.osm.121
perl parseOSMFile.pl  c:\temp\switzerland.osm.122
perl parseOSMFile.pl  c:\temp\switzerland.osm.123
perl parseOSMFile.pl  c:\temp\switzerland.osm.124
perl parseOSMFile.pl  c:\temp\switzerland.osm.125
perl parseOSMFile.pl  c:\temp\switzerland.osm.126
perl parseOSMFile.pl  c:\temp\switzerland.osm.127
perl parseOSMFile.pl  c:\temp\switzerland.osm.128
perl parseOSMFile.pl  c:\temp\switzerland.osm.129
perl parseOSMFile.pl  c:\temp\switzerland.osm.130
perl parseOSMFile.pl  c:\temp\switzerland.osm.131
perl parseOSMFile.pl  c:\temp\switzerland.osm.132
perl parseOSMFile.pl  c:\temp\switzerland.osm.133
perl parseOSMFile.pl  c:\temp\switzerland.osm.134
perl parseOSMFile.pl  c:\temp\switzerland.osm.135
perl parseOSMFile.pl  c:\temp\switzerland.osm.136
perl parseOSMFile.pl  c:\temp\switzerland.osm.137
perl parseOSMFile.pl  c:\temp\switzerland.osm.138
perl parseOSMFile.pl  c:\temp\switzerland.osm.139
perl parseOSMFile.pl  c:\temp\switzerland.osm.140
perl parseOSMFile.pl  c:\temp\switzerland.osm.141
perl parseOSMFile.pl  c:\temp\switzerland.osm.142
perl parseOSMFile.pl  c:\temp\switzerland.osm.143
perl parseOSMFile.pl  c:\temp\switzerland.osm.144
perl parseOSMFile.pl  c:\temp\switzerland.osm.145
perl parseOSMFile.pl  c:\temp\switzerland.osm.146
perl parseOSMFile.pl  c:\temp\switzerland.osm.147
perl parseOSMFile.pl  c:\temp\switzerland.osm.148
perl parseOSMFile.pl  c:\temp\switzerland.osm.149
perl parseOSMFile.pl  c:\temp\switzerland.osm.150
perl parseOSMFile.pl  c:\temp\switzerland.osm.151
perl parseOSMFile.pl  c:\temp\switzerland.osm.152
perl parseOSMFile.pl  c:\temp\switzerland.osm.153
perl parseOSMFile.pl  c:\temp\switzerland.osm.154
perl parseOSMFile.pl  c:\temp\switzerland.osm.155
perl parseOSMFile.pl  c:\temp\switzerland.osm.156
perl parseOSMFile.pl  c:\temp\switzerland.osm.157
perl parseOSMFile.pl  c:\temp\switzerland.osm.158
perl parseOSMFile.pl  c:\temp\switzerland.osm.159
perl parseOSMFile.pl  c:\temp\switzerland.osm.160
perl parseOSMFile.pl  c:\temp\switzerland.osm.161
perl parseOSMFile.pl  c:\temp\switzerland.osm.162
perl parseOSMFile.pl  c:\temp\switzerland.osm.163
perl parseOSMFile.pl  c:\temp\switzerland.osm.164
perl parseOSMFile.pl  c:\temp\switzerland.osm.165
perl parseOSMFile.pl  c:\temp\switzerland.osm.166
perl parseOSMFile.pl  c:\temp\switzerland.osm.167
perl parseOSMFile.pl  c:\temp\switzerland.osm.168
perl parseOSMFile.pl  c:\temp\switzerland.osm.169
perl parseOSMFile.pl  c:\temp\switzerland.osm.170
perl parseOSMFile.pl  c:\temp\switzerland.osm.171
perl parseOSMFile.pl  c:\temp\switzerland.osm.172
perl parseOSMFile.pl  c:\temp\switzerland.osm.173
perl parseOSMFile.pl  c:\temp\switzerland.osm.174
perl parseOSMFile.pl  c:\temp\switzerland.osm.175
perl parseOSMFile.pl  c:\temp\switzerland.osm.176
perl parseOSMFile.pl  c:\temp\switzerland.osm.177
perl parseOSMFile.pl  c:\temp\switzerland.osm.178
perl parseOSMFile.pl  c:\temp\switzerland.osm.179
perl parseOSMFile.pl  c:\temp\switzerland.osm.180
perl parseOSMFile.pl  c:\temp\switzerland.osm.181
perl parseOSMFile.pl  c:\temp\switzerland.osm.182
perl parseOSMFile.pl  c:\temp\switzerland.osm.183
perl parseOSMFile.pl  c:\temp\switzerland.osm.184
perl parseOSMFile.pl  c:\temp\switzerland.osm.185
perl parseOSMFile.pl  c:\temp\switzerland.osm.186
perl parseOSMFile.pl  c:\temp\switzerland.osm.187
perl parseOSMFile.pl  c:\temp\switzerland.osm.188
perl parseOSMFile.pl  c:\temp\switzerland.osm.189
perl parseOSMFile.pl  c:\temp\switzerland.osm.190
perl parseOSMFile.pl  c:\temp\switzerland.osm.191
perl parseOSMFile.pl  c:\temp\switzerland.osm.192
perl parseOSMFile.pl  c:\temp\switzerland.osm.193
perl parseOSMFile.pl  c:\temp\switzerland.osm.194
perl parseOSMFile.pl  c:\temp\switzerland.osm.195
perl parseOSMFile.pl  c:\temp\switzerland.osm.196
perl parseOSMFile.pl  c:\temp\switzerland.osm.197
perl parseOSMFile.pl  c:\temp\switzerland.osm.198
perl parseOSMFile.pl  c:\temp\switzerland.osm.199
perl parseOSMFile.pl  c:\temp\switzerland.osm.200
perl parseOSMFile.pl  c:\temp\switzerland.osm.201
perl parseOSMFile.pl  c:\temp\switzerland.osm.202
perl parseOSMFile.pl  c:\temp\switzerland.osm.203
perl parseOSMFile.pl  c:\temp\switzerland.osm.204
perl parseOSMFile.pl  c:\temp\switzerland.osm.205
perl parseOSMFile.pl  c:\temp\switzerland.osm.206
perl parseOSMFile.pl  c:\temp\switzerland.osm.207
perl parseOSMFile.pl  c:\temp\switzerland.osm.208
perl parseOSMFile.pl  c:\temp\switzerland.osm.209
perl parseOSMFile.pl  c:\temp\switzerland.osm.210
perl parseOSMFile.pl  c:\temp\switzerland.osm.211
perl parseOSMFile.pl  c:\temp\switzerland.osm.212
perl parseOSMFile.pl  c:\temp\switzerland.osm.213
perl parseOSMFile.pl  c:\temp\switzerland.osm.214
perl parseOSMFile.pl  c:\temp\switzerland.osm.215
perl parseOSMFile.pl  c:\temp\switzerland.osm.216
perl parseOSMFile.pl  c:\temp\switzerland.osm.217
perl parseOSMFile.pl  c:\temp\switzerland.osm.218
perl parseOSMFile.pl  c:\temp\switzerland.osm.219
perl parseOSMFile.pl  c:\temp\switzerland.osm.220
perl parseOSMFile.pl  c:\temp\switzerland.osm.221
perl parseOSMFile.pl  c:\temp\switzerland.osm.222
perl parseOSMFile.pl  c:\temp\switzerland.osm.223
perl parseOSMFile.pl  c:\temp\switzerland.osm.224
perl parseOSMFile.pl  c:\temp\switzerland.osm.225
perl parseOSMFile.pl  c:\temp\switzerland.osm.226
perl parseOSMFile.pl  c:\temp\switzerland.osm.227
perl parseOSMFile.pl  c:\temp\switzerland.osm.228
perl parseOSMFile.pl  c:\temp\switzerland.osm.229
perl parseOSMFile.pl  c:\temp\switzerland.osm.230
perl parseOSMFile.pl  c:\temp\switzerland.osm.231
perl parseOSMFile.pl  c:\temp\switzerland.osm.232
perl parseOSMFile.pl  c:\temp\switzerland.osm.233
perl parseOSMFile.pl  c:\temp\switzerland.osm.234
perl parseOSMFile.pl  c:\temp\switzerland.osm.235
perl parseOSMFile.pl  c:\temp\switzerland.osm.236
perl parseOSMFile.pl  c:\temp\switzerland.osm.237
perl parseOSMFile.pl  c:\temp\switzerland.osm.238
perl parseOSMFile.pl  c:\temp\switzerland.osm.239
perl parseOSMFile.pl  c:\temp\switzerland.osm.240
perl parseOSMFile.pl  c:\temp\switzerland.osm.241
perl parseOSMFile.pl  c:\temp\switzerland.osm.242
perl parseOSMFile.pl  c:\temp\switzerland.osm.243
perl parseOSMFile.pl  c:\temp\switzerland.osm.244
perl parseOSMFile.pl  c:\temp\switzerland.osm.245
perl parseOSMFile.pl  c:\temp\switzerland.osm.246
perl parseOSMFile.pl  c:\temp\switzerland.osm.247
perl parseOSMFile.pl  c:\temp\switzerland.osm.248
perl parseOSMFile.pl  c:\temp\switzerland.osm.249
perl parseOSMFile.pl  c:\temp\switzerland.osm.250
perl parseOSMFile.pl  c:\temp\switzerland.osm.251
perl parseOSMFile.pl  c:\temp\switzerland.osm.252
perl parseOSMFile.pl  c:\temp\switzerland.osm.253
perl parseOSMFile.pl  c:\temp\switzerland.osm.254
perl parseOSMFile.pl  c:\temp\switzerland.osm.255
perl parseOSMFile.pl  c:\temp\switzerland.osm.256
perl parseOSMFile.pl  c:\temp\switzerland.osm.257
perl parseOSMFile.pl  c:\temp\switzerland.osm.258
perl parseOSMFile.pl  c:\temp\switzerland.osm.259
perl parseOSMFile.pl  c:\temp\switzerland.osm.260
perl parseOSMFile.pl  c:\temp\switzerland.osm.261
perl parseOSMFile.pl  c:\temp\switzerland.osm.262
perl parseOSMFile.pl  c:\temp\switzerland.osm.263
perl parseOSMFile.pl  c:\temp\switzerland.osm.264
perl parseOSMFile.pl  c:\temp\switzerland.osm.265
perl parseOSMFile.pl  c:\temp\switzerland.osm.266
perl parseOSMFile.pl  c:\temp\switzerland.osm.267
perl parseOSMFile.pl  c:\temp\switzerland.osm.268
perl parseOSMFile.pl  c:\temp\switzerland.osm.269
perl parseOSMFile.pl  c:\temp\switzerland.osm.270
perl parseOSMFile.pl  c:\temp\switzerland.osm.271
perl parseOSMFile.pl  c:\temp\switzerland.osm.272
perl parseOSMFile.pl  c:\temp\switzerland.osm.273
perl parseOSMFile.pl  c:\temp\switzerland.osm.274
perl parseOSMFile.pl  c:\temp\switzerland.osm.275
perl parseOSMFile.pl  c:\temp\switzerland.osm.276
perl parseOSMFile.pl  c:\temp\switzerland.osm.277
perl parseOSMFile.pl  c:\temp\switzerland.osm.278
perl parseOSMFile.pl  c:\temp\switzerland.osm.279
perl parseOSMFile.pl  c:\temp\switzerland.osm.280
perl parseOSMFile.pl  c:\temp\switzerland.osm.281
perl parseOSMFile.pl  c:\temp\switzerland.osm.282
perl parseOSMFile.pl  c:\temp\switzerland.osm.283
perl parseOSMFile.pl  c:\temp\switzerland.osm.284
perl parseOSMFile.pl  c:\temp\switzerland.osm.285
perl parseOSMFile.pl  c:\temp\switzerland.osm.286
perl parseOSMFile.pl  c:\temp\switzerland.osm.287
perl parseOSMFile.pl  c:\temp\switzerland.osm.288
perl parseOSMFile.pl  c:\temp\switzerland.osm.289
perl parseOSMFile.pl  c:\temp\switzerland.osm.290
perl parseOSMFile.pl  c:\temp\switzerland.osm.291
perl parseOSMFile.pl  c:\temp\switzerland.osm.292
